### ISSUE TITLE
ワイヤーフレーム作成

### ISSUE THREAD

**Issue by takashi1coq** [omoushi/tamakonchi#11]
デザインもろもろ
目的無いと作れないから結局企画書になりそう

**Comment by h-haraguchi** [comment]
メニューやキャラクター画面、画面遷移などは目的がないとどれが必要なのかがはっきりしないから作れないということだよね。
一応、以下の要件とワイヤーフレームだけを前提として作ることってできんかな？

- 最初はたまご。
- ある条件でうまれる。
- ある条件で機嫌が変わる。
- ある条件で健康状態が変わる。
- ある条件満たすと進化する。
- ある条件満たしていないとお亡くなりになる。

**Comment by takashi1coq** [comment]
概念すぎてイメージわかないかなぁ
面白そうに感じないからモチベーション上がらないのが正直なところ笑
俺がもうちょっと具体性がほしいから、画面イメージと一緒にあげてしまおうかと思う
おじゃんになっても文句言わないから、やってみるわ

**Comment by h-haraguchi** [comment]
風呂でいろいろ考えたが、企画はあるうちに言語化したほうがいいと思ったからやっぱ企画書でもいいわ。
モチベはだいじやな。

**Comment by takashi1coq** [comment]
|キャラ画面|図鑑画面|図鑑詳細画面|
|:-:|:-:|:-:|
|![キャラ画面](https://user-images.githubusercontent.com/20897975/56540337-67611100-65a3-11e9-9e5c-0a7f9f37bf11.png)|![図鑑画面](https://user-images.githubusercontent.com/20897975/56540352-73e56980-65a3-11e9-82be-ff8c3ac7e7be.png)|![図鑑詳細画面](https://user-images.githubusercontent.com/20897975/56540376-88296680-65a3-11e9-8242-935ba34971e3.png)|

### 進化画面

|動物がやってきた|ポケモン風|
|:-:|:-:|
|![進化画面](https://user-images.githubusercontent.com/20897975/56540406-9bd4cd00-65a3-11e9-811d-d127c873e062.png)|![進化画面2](https://user-images.githubusercontent.com/20897975/56540407-9d05fa00-65a3-11e9-9e23-f3e446a388dc.png)|

**Comment by takashi1coq** [comment]
### みんなの意見。若干アレンジ

- メンヘラを殺さないようにする
- 条件でやってくる動物が変わり、旧キャラが食べられる（食物連鎖A）
- ランダムに動物がやってきて戦って負ける（または食べられる大きさだと）と進化する（食物連鎖B）
- ※今回のワイヤーフレームであんまし考慮してなかった
    - 体のパーツをえらんで徐々に人間になっていく
    - 目玉が最終的に目玉のおやじになる

### 2つに分類した

- 分岐進化
    - 通常の進化体系
    - 複数のパターンを条件によって分岐する
    - 木構造的にキャラとパターンを考える必要がある

- 状態変異
    - 基準となるキャラが変化することによって新しいキャラになる
    - 条件と結果だけを足していけばよいはずなので、楽？

|状態変異|分岐進化|
|:-|:-|
|メンヘラを殺さないようにする<br>体のパーツをえらんで徐々に人間になっていく<br>食物連鎖B|目玉が最終的に目玉のおやじになる<br>食物連鎖A|

### 目的や概要を調整(独断)

- 目的
    - キャラを育てる(育成)
    - 図鑑を埋める（コレクター）
- 画面について
    - 最初のキャラ選択は行わない。後々の実装にする
    - 状態変異の場合、食物連鎖B以外は進化画面を実装しない。気づいたら変化している
    - 図鑑
        - 状態変異 -> 記録する図鑑
            - 食物連鎖Bの場合、分岐構造も記録した方がいいかも
        - 分岐進化 -> 解放する図鑑

### 画面の説明

- キャラ画面
    - えさやり(食事)
    - 片付け(トイレ)
        - 糞尿の処理
        - 散らばったカミソリをしまうなど
    - 状態変異を促す固有の操作
        - トレーニング
        - 撫でる(よろこぶ)
        - 自尊心を満たしてあげる
            - タップするたびに「いいね」「かわいいよ」「ボクは好きだな」

- 図鑑詳細画面
    - タイムスタンプや名前や説明があるとよき
    - 一応ページング、状態変化の場合、ページ追加のイメージなので考慮が楽？

- 進化画面
    - ムービーちっく
        - 動物がやってきた
        - 進化する(ポケモン音外し)

**Comment by h-haraguchi** [comment]
出てきた意見

- 「メンヘラは仕事奪われると病む」という要素を入れたい（長期休暇など）

**Comment by h-haraguchi** [comment]
具体化をよろしく！
