### ISSUE TITLE
React-routerの導入

### ISSUE THREAD

**Issue by kyokoshimizu** [omoushi/tamakonchi#14]
https://github.com/omoushi/tamakonchi/issues/6
React-routerを入れます。

**Comment by kyokoshimizu** [comment]
### 4-23に話したいこと
* react-router-native v5入れました
* react-router-domは入れてないけど問題ないか確認したい
　https://github.com/ReactTraining/react-router
* ローカルでtamakonchi起動できたのですが、Simulatorでtamakonchiではない画面が開いてしまうのでちょっと聞きたい
* プルリクとかのルールあったら聞きたい

**Comment by h-haraguchi** [comment]
プルリクのルールについては特に決めてないっす。唯一決めてることは、みんなが承認したらマージできるということのみ！

**Comment by h-haraguchi** [comment]
react-router-nativeはこれかな？

https://github.com/jmurzy/react-router-native

**Comment by h-haraguchi** [comment]
おそらくだけど、react-router-domはなくて大丈夫だと思う。domってhtmlの概念だから、native(iOSとかandroid)では使われないんじゃないかなぁと思う。iOSとかではビューのコンポーネントはhtmlじゃなくてreact-nativeのコンポーネント使ってるし。

**Comment by kyokoshimizu** [comment]
> react-router-nativeはこれかな？

自分はこれみてましたが、install方法は同じみたいので一緒ぽいです
https://github.com/ReactTraining/react-router/tree/master/packages/react-router-native

**Comment by kyokoshimizu** [comment]
> おそらくだけど、react-router-domはなくて大丈夫だと思う。domってhtmlの概念だから、native(iOSとかandroid)では使われないんじゃないかなぁと思う。iOSとかではビューのコンポーネントはhtmlじゃなくてreact-nativeのコンポーネント使ってるし。

確認ありがとうございます！
