### ISSUE TITLE
2019-04-10 meeting

### ISSUE THREAD

**Issue by tronperidot** [omoushi/tamakonchi#2]
# Agenda

- 要件を考える
- 担当を決める
- 次までにやること決める
- 次に集まる日を決める

- GWの予定

## Other

何かあれば

**Comment by h-haraguchi** [comment]
### おそらく最初の要件

- 最初はたまご。
- ある条件でうまれる。
- ある条件で機嫌が変わる。
- ある条件で健康状態が変わる。
- ある条件満たすと進化する。
- ある条件満たしていないとお亡くなりになる。

**Comment by tronperidot** [comment]
決まっていった内容はwikiに書きたい
https://github.com/omoushi/tamakonchi/wiki/%E4%BB%95%E6%A7%98

**Comment by kyokoshimizu** [comment]
* 今日決めたいこと
** 要件決め
** GW

**Comment by h-haraguchi** [comment]
皆さんToDoができているということで本課題はクローズします。
