### ISSUE TITLE
テストが落ちた時に通知されていない

### ISSUE THREAD

**Issue by tronperidot** [omoushi/tamakonchi#27]
プルリク作ってテスト走ったけど落ちた時にslackに通知されていなかった。なんでだろうね。

**Comment by h-haraguchi** [comment]
Team「omoushi」> settings > Installed GitHub Apps > Travis CI の設定でチェック対象のリポジトリに tamakonchi がなくなってた。

**Comment by h-haraguchi** [comment]
この件については設定をし直すことで解決した。

それとは別で、Slackでも通知したいなと少し思った。

**Comment by h-haraguchi** [comment]
githubとtravis-ciの連携ができてないせいで溜まっていたgreenkeeperのバージョンアップブランチをすべてマージした。
