### ISSUE TITLE
React Nativeで出来ることの調査

### ISSUE THREAD

**Issue by tronperidot** [omoushi/tamakonchi#3]
主にデバイス周りを調べときたい。

**Comment by tronperidot** [comment]
永続化はLocalStorageのラップAPIが提供されていた。
https://facebook.github.io/react-native/docs/asyncstorage#docsNav

**Comment by h-haraguchi** [comment]
標準で提供されてるものがあるのか

**Comment by tronperidot** [comment]
満足した
