### ISSUE TITLE
App.tsxのテストはなんのテストをするべきか

### ISSUE THREAD

**Issue by tronperidot** [omoushi/tamakonchi#39]
react-navigateionをmock化してappそのものテストしかしていなかった
そこにpagerのコンポーネントが入ってライフサイクルのテストが混じってきた。
どうしよう

**Comment by h-haraguchi** [comment]
個人的にはAppも単体としてテストさせたいな。
Pagerの空mockが呼ばれるだけのテスト。
snapshot出力だけする感じで。

**Comment by tronperidot** [comment]
それでいいと思う。
後学のために統合テストとかを作るとしたらどこに作る予定なのかは聞きたいな

**Comment by h-haraguchi** [comment]
個人的には個人的には`__tests__`とは別の場所にしたいなと思ってる。`__integration_tests__`とか？

**Comment by tronperidot** [comment]
そうだね、おkそれでいいと思ってる！

**Comment by tronperidot** [comment]
pagerのテスト作ったら終わりにする
