### ISSUE TITLE
2019-04-16 meeting

### ISSUE THREAD

**Issue by kyokoshimizu** [omoushi/tamakonchi#6]
### Agenda
* 先週の作業報告
* 目的・方向性を決める
* その他

**Comment by h-haraguchi** [comment]
俺はプルリク作っといたので承認よろしく〜
#4

**Comment by h-haraguchi** [comment]
## 議事録
### 誰が何をやるか
- React-routerの導入: @kyokoshimizu 
- 画像とかのリソース取ってくる処理部分(インフラ系): @tronperidot 
- フローチャートの実装: @h-haraguchi 
- 画面のワイヤーフレーム: @takashi1coq 

つまり、
- 機構: @kyokoshimizu 
- インフラ: @tronperidot 
- ドメイン: @h-haraguchi 
- デザイン: @takashi1coq
